# Generated by Django 5.0.4 on 2024-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_request',
            field=models.TextField(null=True),
        ),
    ]
