# Generated by Django 5.0.4 on 2024-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0005_reviewuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_user',
            field=models.ImageField(default=None, upload_to='user_profile_photo'),
        ),
    ]
