# Generated by Django 5.0.4 on 2024-04-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0006_user_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='products_photos')),
            ],
        ),
    ]
