# Generated by Django 5.0.4 on 2024-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0009_basketuser_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='number_order',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='basketuser',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
