# Generated by Django 5.0.4 on 2024-04-06 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0010_orderuser_user_number_order_alter_basketuser_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='orderuser',
            name='number_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='summa_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='status_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CommonApp.orderstatus'),
        ),
    ]
