# Generated by Django 5.0.4 on 2024-04-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0011_orderstatus_orderuser_number_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuser',
            name='status_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CommonApp.orderstatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_order',
            field=models.IntegerField(default=0),
        ),
    ]
