# Generated by Django 5.0.4 on 2024-04-06 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0012_alter_orderuser_status_order_alter_user_number_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 1, 11, 4, 47686)),
        ),
    ]
