# Generated by Django 5.0.4 on 2024-05-20 20:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0013_orderuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuser',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 23, 11, 30, 44746)),
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='status_order',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='CommonApp.orderstatus'),
        ),
    ]
