# Generated by Django 5.0.4 on 2024-05-30 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonApp', '0014_alter_orderuser_date_alter_orderuser_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuser',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 31, 0, 50, 37, 491149)),
        ),
    ]
